# version: '3.8' 
services:
  # Сервіс 1: Фронтенд (Nginx)
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./css:/usr/share/nginx/html/css
      - ./images:/usr/share/nginx/html/images
      - ./js:/usr/share/nginx/html/js
      - ./index.html:/usr/share/nginx/html/index.html
      - ./menu.html:/usr/share/nginx/html/menu.html
      - ./gallery.html:/usr/share/nginx/html/gallery.html
      - ./contact.html:/usr/share/nginx/html/contact.html
    depends_on:
      - api 

  # Сервіс 2: Бек-енд (API на Node.js)
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      
  # Сервіс 3: База Даних (PostgreSQL)
  db:
    image: postgres:16-alpine 
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
       ["5433:5432"] 

volumes:
  postgres_data: